[functions.create-subscription]
verify_jwt = false

[functions.payment-methods]
verify_jwt = false

[functions.mercadopago-webhook]
verify_jwt = false

[functions.extract-recipe-details]
verify_jwt = false
